import "../util";
import * as fs from "node:fs/promises";
import { solve as solve1 } from "./star1";
import { solve as solve2 } from "./star2";
import { parse } from "./parse";
const calDate = process.env.CAL_DATE;

console.log(`running day ${calDate}`);

const file = await fs.readFile(`./src/day${calDate}/data.txt`, "utf8");
/* cSpell:disable */
const example = `
        ...#
        .#..
        #...
        ....
...#.......#
........#...
..#....#....
..........#.
        ...#....
        .....#..
        .#......
        ......#.

10R5L5R10L4R5L5`.substring(1);
const exampleX = `
        ....
        ....
        ....
        ....
............
............
............
............
        ........
        ........
        ........
        ........

14`.substring(1);
const exampleB = `
    ........
    ........
    ........
    ........
    ....
    ....
    ....
    ....
........
........
........
........
....
....
....
....

16L1R16L1R16L1R16L1R16L1R16L1R16L1R16`.substring(1);
/* cSpell:enable */
let doReal = false;
doReal = true;

const input = parse(doReal ? file : example);
// input.start = [0, 0];
// input.dir = "^";
// console.time("star1");
// console.log("The solution to star 1 is:", solve1(input));
// console.timeEnd("star1");

console.time("star2");
console.log("The solution to star 2 is:", solve2(input));
console.timeEnd("star2");

/*
 expected

        >>v#    
        .#v.    
        #.v.    
        ..v.    
...#..^...v#    
.>>>>>^.#.>>    
.^#....#....    
.^........#.    
        ...#..v.
        .....#v.
        .#v<<<<.
        ..v...#.
*/
